### ISSUE TITLE
Use polyfill for requestAnimationFrame

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-euler#9]
Find a polyfill module on npm for `requestAnimationFrame()`.  Use that instead of direct calls to `window.requestAnimationFrame()` in `layout/index.js`.

**Comment by PikioopSo** [comment]
Hi @maxfranz, window.requestAnimationFrame() sounds real neat, I found some info about some gists but have never tested.   

I actually am interested in contributing during mozsprint and beyond so that I can start implementing cytoscape into it. I have a question though...I was going to use a method I call the ***addIntervalListener()*** which I built up in various builds from other web experiments.  

If you would like to see what that is I'd be happy to show you.  Also, I was wondering if you had a diff. forum so projects that are using cytoscape can introduce themselves as new projects?

**Comment by maxkfranz** [comment]
@PiReel, that sounds great.  Thanks for your interest in the project!  Worst case, I think there should also be a very basic raf polyfill in `cytoscape.js/src/util` that could be copied.  It would be nicer to have a dependency on an npm module so both the main lib and this layout could share the same dependency.

There's https://github.com/cytoscape/cytoscape.js/issues/914 for listing projects that use Cytoscape.js.  Is that what you're looking for, or are you thinking of something else?

**Comment by PikioopSo** [comment]
Thanks for the information @maxkfranz, I'll put down issues related to this on the repo, so I can track changes to requestAnimationFrame() and cytoscape, too.

Edit -- thanks for the #914 link, that was exactly what I was looking for.
